### ISSUE TITLE
Add xonsh shell support

### ISSUE THREAD

**Issue by anki-code** [dylanjcastillo/shell-genie#10]
It will be cool to have an ability to set the shell (e.g. https://xon.sh) i.e.:
```xsh
xonsh
$SHELL_GENIE_SHELL="xonsh"
shell-genie ask "set env variable HELLO with "world" value"  # automatically added "on xonsh"
# Command: $HELLO="world"
# Do you want to run this command? [y/n]:
```

**Comment by b0bd3v** [comment]
I think this can be modified in the config file.

![Screenshot from 2023-05-10 10-48-07](https://github.com/dylanjcastillo/shell-genie/assets/3808448/f48f92b5-bbc4-4f60-91bf-3eb9e79d4826)

**Comment by dylanjcastillo** [comment]
Yes, @b0bd3v is correct.
