### ISSUE TITLE
/too bad it doesn't work with the latest pyton

### ISSUE THREAD

**Issue by kersvanbinsbergen** [dylanjcastillo/shell-genie#11]
Nice!

/too bad it doesn't work with the latest pyton. 3.8.10

PIP STDOUT
----------

PIP STDERR
----------
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.10,<4.0; 0.1.1 Requires-Python >=3.10,<4.0; 0.1.2 Requires-Python >=3.10,<4.0; 0.1.3 Requires-Python >=3.10,<4.0; 0.1.4 Requires-Python >=3.10,<4.0; 0.1.5 Requires-Python >=3.10,<4.0; 0.1.6 Requires-Python >=3.10,<4.0; 0.2.0 Requires-Python >=3.10,<4.0; 0.2.1 Requires-Python >=3.10,<4.0; 0.2.10 Requires-Python >=3.10,<4.0; 0.2.2 Requires-Python >=3.10,<4.0; 0.2.3 Requires-Python >=3.10,<4.0; 0.2.4 Requires-Python >=3.10,<4.0; 0.2.5 Requires-Python >=3.10,<4.0; 0.2.6 Requires-Python >=3.10,<4.0; 0.2.7 Requires-Python >=3.10,<4.0; 0.2.8 Requires-Python >=3.10,<4.0; 0.2.9 Requires-Python >=3.10,<4.0

ERROR: Could not find a version that satisfies the requirement shell-genie (from versions: none)
ERROR: No matching distribution found for shell-genie

**Comment by b0bd3v** [comment]
🤔 It's works with python 3.10.6.

**Comment by dylanjcastillo** [comment]
Sorry, but I haven't found time to make versions with older python versions.
