### ISSUE TITLE
Where is the GPT-server (self-hosting) code?

### ISSUE THREAD

**Issue by justingoldberg** [dylanjcastillo/shell-genie#12]
Or do you recommend one of these?

https://www.google.com/search?q=site%3Agithub.com+gpt+api+self+hosted&oq=site%3Agithub.com+gpt+api+self+hosted&aqs=chrome..69i57j69i58.6678j0j7&sourceid=chrome&ie=UTF-8

**Comment by dylanjcastillo** [comment]
Hi,

I'll try to make an implementation available soon.

Best,
Dylan
