### ISSUE TITLE
--explain 

### ISSUE THREAD

**Issue by olofnuggts** [dylanjcastillo/shell-genie#13]
everytime i run for example : shell-genie ask "list file" --explain
i get Error: Error in response.
any idea why ?

**Comment by dylanjcastillo** [comment]
Hard to know if you don't provide more details. It's working for me:

<img width="690" alt="image" src="https://github.com/dylanjcastillo/shell-genie/assets/7218756/44ad2a95-8550-42bd-bfd2-d5a8d4eee581">

**Comment by Kiraaliraa** [comment]
It does happen with certain prompts. For example:
```shell
~> shell-genie ask "reinstall a package through pacman"
Error: Error in response.

shell-genie ask "reinstall a package through pacman"
Error: Error in response.
``` 
weirdly though this worked:
```shell
"reinstall a package"
Command: sudo pacman -S <package_name> --overwrite <file_to_overwrite>
```
