### ISSUE TITLE
Remove GPT-3.5 Turbo support and add free alternative support

### ISSUE THREAD

**Issue by KarthiDreamr** [dylanjcastillo/shell-genie#16]
GPT-3.5 Turbo OpenAI API key is no longer free under rate limit. As of March 8, 2023, OpenAI moved the GPT-3.5 Turbo model to their paid tier. This means that you will need to upgrade to a paid plan to use the GPT-3.5 Turbo model, even if you are only using it under the rate limit.

Here are some alternatives to the GPT-3.5 Turbo model that are still free under rate limit:

GPT-3 Ada
GPT-3 Babbage
ChatGPT
You can also try other large language models, such as:

Bard
Jurassic-1 Jumbo
Megatron-Turing NLG

**Comment by dylanjcastillo** [comment]
GPT-3.5-turbo has never been free. The models listed there aren’t either.
