### ISSUE TITLE
Allow later openai

### ISSUE THREAD

**Issue by fabaff** [dylanjcastillo/shell-genie#2]
`openai` is [constantly evolving](https://github.com/openai/openai-python/releases). `shell-genie` has a constraint for `openai`: 

https://github.com/dylanjcastillo/shell-genie/blob/d6da42a4426e6058a0b5ae07837d8c003cd1239e/pyproject.toml#L15

This requires all distributions which are shipping `shell-genie` to relax the constraint. Would it be possible to do that here?

Thanks

**Comment by dylanjcastillo** [comment]
Makes sense, just pushed that change. Thank you!

**Comment by fabaff** [comment]
Thank you.
