### ISSUE TITLE
Does not pass entered shell to configuration setup.

### ISSUE THREAD

**Issue by alastairhm** [dylanjcastillo/shell-genie#23]
https://github.com/dylanjcastillo/shell-genie/blob/c9991375fa72c7528b1176a25b139abebaf00150/shell_genie/main.py#L60

Does not seem to pass the entered shell asked for when SHELL environment variable is not set to the configuration setup.

![image](https://github.com/dylanjcastillo/shell-genie/assets/214005/b7d780d5-a859-4bca-89db-ef3eee285e7b)

**Comment by dylanjcastillo** [comment]
Hi, I'm going to archive this repository. Please consider using an alternative such as ShellGPT: https://github.com/TheR1D/shell_gpt
