### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by fabaff** [dylanjcastillo/shell-genie#3]
Currently there is no license statement. Could you please add a `LICENSE` file that contains the license text or add details to `pyproject.toml`?

For Nixpkgs `shell-genie` is marked as `unfree` for now but a clarification about the license would be much appreciated.

Thanks.

**Comment by dylanjcastillo** [comment]
Hey @fabaff, I just added the license (MIT). Let me know if this fixes the issue.

**Comment by fabaff** [comment]
Thank you.
