### ISSUE TITLE
Shell-genie init returns command not found

### ISSUE THREAD

**Issue by et-the-extra-terrestrial** [dylanjcastillo/shell-genie#4]
Despite following all the installation instructions, the instruction shell-genie init returns error: command not found.

**Comment by dylanjcastillo** [comment]
Hey @et-the-extra-terrestrial,

how did you install it? Using pipx or in a virtual environment.

Can you run `which shell-genie` and tell me what's the output?

**Comment by et-the-extra-terrestrial** [comment]
Using pipx on Ubuntu 22.04LTS in VirtualBox.

which shell-genie returns this: `/home/user/.local/bin/shell-genie`

**Comment by dylanjcastillo** [comment]
Sorry for the late reply, does it work if you run `/home/user/.local/bin/shell-genie init`?

**Comment by et-the-extra-terrestrial** [comment]
It works! Awesome!

**Comment by dylanjcastillo** [comment]
You probably need to add that directory to the path ` export PATH=$PATH:$HOME/.local/bin` in your `.bashrc` if you want to just type `shell-genie` instead of writing the full path.
