### ISSUE TITLE
Integrate with Bash/ZSH auto-completion

### ISSUE THREAD

**Issue by yuri-ccp** [dylanjcastillo/shell-genie#5]
This may end a bit hard to do but could be very usefull to allows shell-genie to works with tabs autocomplete dedution and explanation like for example. If you write "ls -lh" and press tab twice to autocomplete it can comes with the response:
`Description: The command 'ls -lh' is used to list the contents of a directory in a long format, with human-readable file sizes. It will display the file permissions, owner, group, size, date, and 
filename. The '-l' flag stands for 'long' and the '-h' flag stands for 'human-readable'. This command works on macOS-12.6.5 using zsh.`

**Comment by dylanjcastillo** [comment]
Sound interesting. Tbh, I'm not really sure how to implement this but will do some research.

I'll close this for now.
