### ISSUE TITLE
Change from OpenAI-GPT3 to Free Genie

### ISSUE THREAD

**Issue by fnandesrafael** [dylanjcastillo/shell-genie#7]
Is it possible to change from gpt3 to free genie after instalation? Or i need to reinstall it? And if so, how do i do?

**Comment by AlexJBSilva** [comment]
Did you try to repeat the [step 1](https://github.com/dylanjcastillo/shell-genie#how-to-use) of istallation?
`shell-genie init`

**Comment by Harsh-br0** [comment]
How's the free genie backend architecture?
Is it calling gpt there too or a custom model?

**Comment by dylanjcastillo** [comment]
@Harsh-br0 It's calling GPT for now!

**Comment by dylanjcastillo** [comment]
@rafaelimaf, you need to re-run `shell-genie init`

**Comment by fnandesrafael** [comment]
It worked! Ty!
