### ISSUE TITLE
Stop to work with open ai in ubuntu 22.04.1.

### ISSUE THREAD

**Issue by b0bd3v** [dylanjcastillo/shell-genie#9]
Hi @dylanjcastillo 

shell-genie stop to work with open ai in ubuntu 22.04.1. With free-genie still work. 

I noticed tha in open ai, show Command: \`ls -d */\` 
and free-genie show Command: ls -d */

It was some update or my mistake?

thx

**Comment by dylanjcastillo** [comment]
Hey @b0bd3v, are you using the latest version (e.g., `openai-gpt-3.5-turbo`?

**Comment by b0bd3v** [comment]
```
{
    'backend': 'openai-gpt-3.5-turbo',
    'os': 'Linux',
    'os_fullname': 'Ubuntu 23.04',
    'shell': 'zsh',
    'openai_api_key':  'xxxx'
}
```

Example

```
$ shell-genie ask "Qual comando para listar arquivos ocultos?"
Command: `ls -a`
Do you want to run the command? [y/n]: y
/bin/sh: 1: .: ..: not found
```

**Comment by b0bd3v** [comment]
This latest comment refers to the procedure being executed on another computer with the latest version of Ubuntu. And the same problem occurred.

**Comment by dylanjcastillo** [comment]
@b0bd3v, the last release should fix this issue!

**Comment by b0bd3v** [comment]
Now it's working. Thank you very much for your help. And thank you for developing this amazing tool.
